sonar.projectKey=fastapi-boilerplate
sonar.projectName=FastAPI Boilerplate
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.language=py

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

# Exclude env + unnecessary files
sonar.exclusions=**/boil/**,**/__pycache__/**

# Coverage (optional but strong)
sonar.python.coverage.reportPaths=coverage.xml